### PR TITLE
applied the root checkstyle format, added comments < layout, document…

### PR DESCRIPTION
**Pull request by ccberg**
…ation

### CODE REVIEW

**Comment by hungnguyen94** [comment]
Looks nice, but still uses tabs. Please use 4 spaces.

**Comment by ccberg** [comment]
removed the tabs, thanks for the review!

**Comment by hungnguyen94** [comment]
Everything seems fixed. Good job. Ruben, please review.

**Comment by rubenwiersma** [comment]
Everything done well according to CheckStyle, some warnings still stand, but will be fixed this sprint.

**Pull request merged**
