### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by rubenwiersma**

### CODE REVIEW

**Comment by trombomart** [comment]
Ziet er goed uit!

**Comment by hungnguyen94** [comment]
Looks good. Requirements seem to be clear.

**Comment by rubenwiersma** [comment]
Thanks guys, this means a lot to me. Especially after my girlfriend broke up with me and I ate three bars of chocolate while watching Grey's Anatomy. I'm glad I'm still able to do something right.

**Comment by hungnguyen94** [comment]
You can always cry on my shoulder.

**Pull request merged**
